# Generated by Django 4.2.5 on 2023-09-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_customer_department_product_suppplier_team_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('lifespan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=500, null=True)),
                ('Vin', models.CharField(max_length=500, null=True, unique=True)),
                ('Amount', models.IntegerField(null=True)),
                ('Odometer', models.IntegerField(null=True)),
                ('Purchase_type', models.CharField(max_length=500, null=True)),
                ('Created_date', models.DateField(auto_now_add=True, null=True)),
                ('PurchaseDate', models.DateField(null=True)),
                ('Cartype', models.CharField(max_length=500, null=True)),
                ('modelyear', models.CharField(max_length=50, null=True)),
                ('Asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindept.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Carspec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='localpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=5000, null=True)),
                ('Car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindept.car')),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=5000, null=True)),
                ('Premium', models.IntegerField()),
                ('Car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindept.car')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindept.insurancevendors')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=50, null=True)),
                ('Car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admindept.car')),
                ('Employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.employees')),
            ],
        ),
        migrations.CreateModel(
            name='carphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=5000, null=True)),
                ('Car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindept.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Carspec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admindept.carspec'),
        ),
        migrations.AddField(
            model_name='car',
            name='Supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.suppplier'),
        ),
    ]
