# Generated by Django 4.2.5 on 2023-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='Premium',
            field=models.IntegerField(null=True),
        ),
    ]
