# Generated by Django 4.2.5 on 2023-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0002_insurance_month_alter_insurance_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Operating_System',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='Storage',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='ram',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
