# Generated by Django 4.2.5 on 2023-09-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0003_car_operating_system_car_storage_car_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stoke',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
