# Generated by Django 4.2.5 on 2023-09-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0004_car_stoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='stoke',
        ),
    ]
