# Generated by Django 4.2.5 on 2023-09-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0007_rename_package_fullpremium_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpaid',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admindept.insurance'),
        ),
    ]
