# Generated by Django 4.2.5 on 2023-09-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0008_alter_premiumpaid_insurance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fullpremium',
            new_name='admintransaction',
        ),
        migrations.RenameField(
            model_name='premiumpaid',
            old_name='fullpremium',
            new_name='transaction',
        ),
    ]
