# Generated by Django 4.2.5 on 2023-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0009_rename_fullpremium_admintransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintransaction',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='admintransaction',
            name='month',
        ),
        migrations.RemoveField(
            model_name='admintransaction',
            name='refernce',
        ),
        migrations.AddField(
            model_name='admintransaction',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='premiumpaid',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admintransaction',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
    ]
