# Generated by Django 4.2.5 on 2023-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0010_remove_admintransaction_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='claim_status',
            field=models.CharField(default='no', max_length=5000),
        ),
        migrations.AddField(
            model_name='insurance',
            name='full_claims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insurance',
            name='full_premium',
            field=models.IntegerField(default=0),
        ),
    ]
