# Generated by Django 4.2.5 on 2023-09-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0011_insurance_claim_status_insurance_full_claims_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='claim_status',
            new_name='premium_status',
        ),
    ]
