# Generated by Django 4.2.5 on 2023-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0012_rename_claim_status_insurance_premium_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpaid',
            name='month',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='premiumpaid',
            name='vendor',
            field=models.IntegerField(null=True),
        ),
    ]
