# Generated by Django 4.2.5 on 2023-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0013_premiumpaid_month_premiumpaid_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpaid',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
