# Generated by Django 4.2.5 on 2023-10-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0019_alter_premiumpaid_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='localpaper',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CarpaperPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('carpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindept.carpaper')),
                ('localpapers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindept.localpaper')),
            ],
        ),
    ]
