# Generated by Django 4.2.5 on 2023-10-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0020_carpaper_localpaper_month_carpaperpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurancepremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('month', models.CharField(max_length=50, null=True)),
                ('Amount', models.IntegerField()),
                ('Status', models.CharField(default='Pending', max_length=500)),
                ('InsuranceVendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindept.insurancevendors')),
            ],
        ),
        migrations.CreateModel(
            name='insurancepremiumitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindept.car')),
                ('InsurancePremium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindept.insurancepremium')),
            ],
        ),
    ]
