# Generated by Django 4.2.5 on 2023-10-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0022_alter_insurancepremium_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bill_num',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='pending', max_length=500),
        ),
    ]
