# Generated by Django 4.2.5 on 2023-10-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0023_car_bill_num_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='payment_num',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
