# Generated by Django 4.2.5 on 2023-11-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0024_car_payment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpaper',
            name='paper',
            field=models.CharField(max_length=5000, null=True, unique=True),
        ),
    ]
