# Generated by Django 4.2.5 on 2023-11-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0025_alter_localpaper_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localpaper',
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarpaperPayment',
        ),
        migrations.DeleteModel(
            name='localpaper',
        ),
    ]
