# Generated by Django 4.2.5 on 2023-11-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0027_localpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepremium',
            name='InsuranceVendor',
        ),
        migrations.RemoveField(
            model_name='insurancepremiumitems',
            name='Asset',
        ),
        migrations.RemoveField(
            model_name='insurancepremiumitems',
            name='InsurancePremium',
        ),
        migrations.RemoveField(
            model_name='premiumpaid',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='premiumpaid',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='admintransaction',
        ),
        migrations.DeleteModel(
            name='insurancepremium',
        ),
        migrations.DeleteModel(
            name='insurancepremiumitems',
        ),
        migrations.DeleteModel(
            name='premiumpaid',
        ),
    ]
