# Generated by Django 4.2.5 on 2023-11-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0028_remove_insurancepremium_insurancevendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
