# Generated by Django 4.2.5 on 2023-11-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0029_insurance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Availability',
            field=models.CharField(default='AVAILABLE', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='Sales_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeecar',
            name='Car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindept.car'),
        ),
    ]
