# Generated by Django 4.2.5 on 2023-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0030_car_availability_car_sales_date_car_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Sales_amount',
            field=models.IntegerField(default=0),
        ),
    ]
