# Generated by Django 4.2.5 on 2023-11-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0031_car_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='staff',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
