# Generated by Django 4.2.5 on 2023-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindept', '0032_insurance_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caryear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
        ),
    ]
