# Generated by Django 4.2.5 on 2023-09-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessName', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=2500)),
                ('createdby', models.CharField(default='nobody', max_length=50)),
                ('Alteredby', models.CharField(default='nobody', max_length=1500)),
                ('createdat', models.DateField(auto_now_add=True)),
                ('alteredat', models.DateField(auto_now=True)),
                ('personnel', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=50)),
                ('Completion_status', models.IntegerField(default=0)),
                ('Balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=1500, null=True)),
                ('Team', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('uom', models.CharField(max_length=50)),
                ('qtyperctn', models.IntegerField()),
                ('createdby', models.CharField(default='nobody', max_length=50)),
                ('Alteredby', models.CharField(default='nobody', max_length=1500)),
                ('createdat', models.DateField(auto_now_add=True)),
                ('alteredat', models.DateField(auto_now=True)),
                ('Price', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suppplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=1500, null=True)),
                ('Last_name', models.CharField(max_length=1500, null=True)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.department')),
            ],
        ),
    ]
